/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koperasisimmpanpinjam.view;

import java.awt.event.ActionListener;
import javax.swing.JTextField;

/**
 *
 * @author Hariadi Adha F
 */
public class ViewAngsuran2 extends javax.swing.JFrame {

    /**
     * Creates new form Angsuran2
     */
    public ViewAngsuran2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtBesarPinjaman = new javax.swing.JLabel();
        inputNamaPinjAngsuran = new javax.swing.JTextField();
        txtTglAngsuran = new javax.swing.JLabel();
        inputTglAngsuran = new javax.swing.JTextField();
        txtJmlAngsur = new javax.swing.JLabel();
        inputAngsAngsuran = new javax.swing.JTextField();
        btnBayarAngsuran = new javax.swing.JButton();
        txtTglDeadline = new javax.swing.JLabel();
        DeadlineAngsuran = new javax.swing.JTextField();
        checkBoxAngsuran = new javax.swing.JCheckBox();
        cbText1Angs = new javax.swing.JLabel();
        txtAngsuran = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(97, 90, 79));

        jPanel2.setBackground(new java.awt.Color(33, 57, 95));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(229, 229, 229));

        txtBesarPinjaman.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        txtBesarPinjaman.setText("Nama Pinjaman");

        inputNamaPinjAngsuran.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        inputNamaPinjAngsuran.setText("Beli Motor");

        txtTglAngsuran.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        txtTglAngsuran.setText("Tanggal");

        inputTglAngsuran.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        inputTglAngsuran.setText("DD/MM/YYYY");
        inputTglAngsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTglAngsuranActionPerformed(evt);
            }
        });

        txtJmlAngsur.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        txtJmlAngsur.setText("Jumlah Angsur");

        inputAngsAngsuran.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        inputAngsAngsuran.setText("Rp.-");

        btnBayarAngsuran.setBackground(new java.awt.Color(102, 0, 51));
        btnBayarAngsuran.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        btnBayarAngsuran.setText("Angsur");
        btnBayarAngsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarAngsuranActionPerformed(evt);
            }
        });

        txtTglDeadline.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        txtTglDeadline.setText("Deadline");

        DeadlineAngsuran.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        DeadlineAngsuran.setText("21/12/2021");
        DeadlineAngsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeadlineAngsuranActionPerformed(evt);
            }
        });

        checkBoxAngsuran.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        checkBoxAngsuran.setText("Dengan ini saya menyatakan setuju dengan jumlah");
        checkBoxAngsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAngsuranActionPerformed(evt);
            }
        });

        cbText1Angs.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        cbText1Angs.setText("yang akan saya angsur");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBesarPinjaman)
                            .addComponent(txtJmlAngsur)
                            .addComponent(txtTglAngsuran)
                            .addComponent(txtTglDeadline))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputTglAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAngsAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNamaPinjAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeadlineAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxAngsuran)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(cbText1Angs)))
                        .addGap(254, 254, 254))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBayarAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBesarPinjaman)
                    .addComponent(inputNamaPinjAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTglAngsuran)
                    .addComponent(inputTglAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTglDeadline)
                    .addComponent(DeadlineAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAngsAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJmlAngsur))
                .addGap(38, 38, 38)
                .addComponent(checkBoxAngsuran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbText1Angs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnBayarAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        txtAngsuran.setFont(new java.awt.Font("Roboto", 1, 64)); // NOI18N
        txtAngsuran.setForeground(new java.awt.Color(255, 255, 255));
        txtAngsuran.setText("Angsuran");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAngsuran)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtAngsuran)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTglAngsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTglAngsuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTglAngsuranActionPerformed

    private void btnBayarAngsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarAngsuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBayarAngsuranActionPerformed

    private void checkBoxAngsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAngsuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAngsuranActionPerformed

    private void DeadlineAngsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeadlineAngsuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeadlineAngsuranActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DeadlineAngsuran;
    private javax.swing.JButton btnBayarAngsuran;
    private javax.swing.JLabel cbText1Angs;
    private javax.swing.JCheckBox checkBoxAngsuran;
    private javax.swing.JTextField inputAngsAngsuran;
    private javax.swing.JTextField inputNamaPinjAngsuran;
    private javax.swing.JTextField inputTglAngsuran;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtAngsuran;
    private javax.swing.JLabel txtBesarPinjaman;
    private javax.swing.JLabel txtJmlAngsur;
    private javax.swing.JLabel txtTglAngsuran;
    private javax.swing.JLabel txtTglDeadline;
    // End of variables declaration//GEN-END:variables

    public String getDeadlineAngsuran() {
        return DeadlineAngsuran.getText();
    }

    public void setDeadlineAngsuran(String DeadlineAngsuran) {
        this.DeadlineAngsuran.setText(DeadlineAngsuran);
    }
    
    //YAZID ZONE//
    
    public String getNamaAngsuran() {
        return inputNamaPinjAngsuran.getText();
    }
    
    public void setNamaAngsuran(String NamaAngsuran) {
        this.inputAngsAngsuran.setText(NamaAngsuran);
    }
    
    public String getInputAngsuran() {
        return inputAngsAngsuran.getText();
    }
    
    public void setInputAngsuran(String AngsAngsuran){
        this.inputAngsAngsuran.setText(AngsAngsuran);
    }
    
    public String getTglAngsuran(){
        return inputTglAngsuran.getText();
    }
    
    public void setTglAngsuran(String TglAngsuran){
        this.inputTglAngsuran.setText(TglAngsuran);
    }
    
    public void addActionListener(ActionListener x){
        btnBayarAngsuran.addActionListener(x);
    }

}
